# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3315efdbb4e0b2738f149519fc6bf0ac613aeb488c45bf206f8b0afa15f906e957edbd4030f6a0f3fc300c086cd4e7e616a290f4f87fbe9edb891a2bc3fa141c

test:
  secret_key_base: 7031e0c16e7e6a25ca5c4c9e7fbc70747b868ca0a9ee5ce0805828e9404abe184ba0fdddf6f548bc9ae78707bf695a10fb0ea9df9f006e2238a40d1fcb945cd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
